#!/sbin/busybox sh

SWAP=/dev/block/vnswap0;
ZRAM=$2;

if [ -f $1 ]; then
	if [[ ! -z $2 ]]; then
		$BB swapoff $SWAP > /dev/null 2>&1;
		
		if [ $ZRAM -gt 0 ]; then
			$BB echo $((ZRAM * 1024 * 1024)) > $1;
			$BB mkswap $SWAP > /dev/null 2>&1;
			$BB swapon $SWAP > /dev/null 2>&1;
		fi;
	fi;
	
	ZRAM=`$BB cat $1`;
	$BB echo $((ZRAM / 1024 / 1024));
else
	$BB echo "0";
fi;
